# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: XrmGhost.Cli
PackageVersion: 1.7.1
PackageLocale: en-US
Publisher: XrmGhost
PublisherUrl: https://www.xrmghost.tech/
PackageName: XrmGhost CLI
PackageUrl: https://docs.xrmghost.tech/cli/
License: Proprietary
LicenseUrl: https://www.xrmghost.tech/legal/xrmghost-license
Copyright: Copyright (c) XrmGhost. All Rights Reserved.
ShortDescription: Command-line interface for XrmGhost plugin execution and environment management.
Moniker: xg
ReleaseNotesUrl: https://github.com/xrmghost/xrmghost/releases/tag/v1.7.1
ManifestType: defaultLocale
ManifestVersion: 1.10.0
