# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: XrmGhost.Cli
PackageVersion: 1.7.5
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: xg.exe
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/xrmghost/xrmghost/releases/download/v1.7.5/xrmghost-cli-1.7.5-full.zip
  InstallerSha256: 42ED2C50E73468D268B4888C2E1ED6F360CB97DF3267E585E904BBED8530D7BD
ManifestType: installer
ManifestVersion: 1.12.0
